### ISSUE TITLE
Testing: ResourceMeta module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ResourceMeta#1]
This new module allows administrators to map resource properties to [metadata elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta). This is helpful for web indexing and search engine optimization (SEO), making public resources more richly described and discoverable.

To test this, install the module and click on the "Resource Meta" link under "Modules." It should take you to a table of all resource templates. Choose a template and click on the pencil icon. It should take you to a table of all properties in that template. Select a few meta names for a few properties (these are multi-selects), and click the "Submit" button. It should take you to a table of all properties in the template, with the new meta names you just selected. Click on the "Edit" button, remove some meta names, add some meta names, and click "Submit." The page should reflect your changes.

Now add a new item, select the resource template you've been using, and enter some data for the properties that you previously mapped to meta names. Enter a few values per property. Use text, URI, and resource data types. Save the item.

Now go to a public site that includes that item, and go to the item's show page. Look at the page source and look for the `<meta>` tags in the `<head>` section. You should see the `<meta>` tags containing `name="..."` and `content="..."` attributes. The name attributes are the meta names you configured when mapping resource templates. The content attributes are the values you entered when editing an item.

**Comment by jimsafley** [comment]
I've added more features that need testing. When editing a Resource Meta resource template, you should see three new buttons:

- Clear: clear all selected meta names
- Reset: reset meta names to their original selections
- Map dcterms: convenience feature to map dcterms meta names to dcterms properties (this will clear existing meta names)

**Comment by allanaaa** [comment]
You shouldn't *need* to add a new item, right? Anything using the resource template should just do it automatically?

This looks fine using the dcterms automap button. I'll try a few variants while I write the docs. 

Was this requested on the forum? Do you have a link? I'd like to have a few use cases to think about.

**Comment by sharonmleon** [comment]
There wasn't much of a post, but it was about Google Scholar indexing: https://forum.omeka.org/t/google-scholar-index/16932

**Comment by jimsafley** [comment]
Yes, it will work automatically for any resource of a particular resource template.

**Comment by allanaaa** [comment]
Resource Meta can be viewed (the configuration interface) by users at any level, and modified by Editors and above. Is that intended?

**Comment by jimsafley** [comment]
Yes, that's the intention. It's identical behavior to the InverseProperties module.

**Comment by allanaaa** [comment]
Text searching in RM is a bit funky - it doesn't look for a string at any position in the results. In this case it looks for a word after a period, but not after an underscore or after, say, "alternate" in "alternateTitle". Can that be improved? 

![RMsearch](https://user-images.githubusercontent.com/28012148/228026172-6b25ba96-0ec2-4b0e-8b00-70bb3eef872f.PNG)

**Comment by jimsafley** [comment]
Unfortunately it cannot be improved. We use [Chosen](https://harvesthq.github.io/chosen/) to enhance the browser's select UI, and the search behavior is baked in.
